# Generated by Django 5.0 on 2025-11-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
