# Generated by Django 5.0 on 2025-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='orderedbooks',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='books',
            field=models.ManyToManyField(related_name='orders', through='app.OrderedBooks', to='app.books'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
